name: Check and Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  check-version-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get current version from manifest.json
      id: get_version
      run: |
        current_version=$(jq -r '.version' main/manifest.json)
        echo "current_version=v$current_version" >> $GITHUB_ENV

    - name: Get latest release version
      id: get_latest_release
      run: |
        latest_version=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name' || echo "0.0.0")
        echo "latest_version=$latest_version" >> $GITHUB_ENV

    - name: Compare versions
      id: compare_versions
      run: |
        if [ "$current_version" != "$latest_version" ]; then
          echo "new_version=true" >> $GITHUB_ENV
        else
          echo "new_version=false" >> $GITHUB_ENV
        fi

    - name: Remove "key" from manifest.json
      run: |
        jq 'del(.key, .background) | .permissions -= ["management"]' main/manifest.json > main/manifest.tmp && mv main/manifest.tmp main/manifest.json

    - name: Zip main directory
      run: |
        cd main && zip -r ../extension.zip .

    - name: Create release
      if: env.new_version == 'true'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.current_version }}
        name: Release ${{ env.current_version }}
        files: extension.zip
